[package]
name = "aizawa"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = {version = "1.0.7"}
pnet = {version = "0.28.0"}
rand = {version = "0.8.4"}
